id: 830201397974663229
name: The Pilot Club
roles:
  - name: Moderator
    id: 849037973064384514
channels:
  - name: Git Channel
    id: 992927027114037308
  - name: Screenshot Contest
    id: 830210202464813056
  - name: Crew Chat
    id: 830209982770708500
emojis:
  - name: TPC Reaction
    id: :tpc:845075689241051138
baseurl:
  - name: FCP
    link: https://flightcrew.thepilotclub.org
  - name: Internal API
    link: https://api.thepilotclub.org